try:
    print(is_good_password('123456789a'))
except Exception as err:
    print(type(err))