@takes_positive
def positive_sum(*args):
    return sum(args)
    
try:
    print(positive_sum(11, 20.7, 10))
except Exception as err:
    print(type(err))