@takes_positive
def positive_sum(*args):
    return sum(args)
    
try:
    print(positive_sum(*range(100, -1, -1)))
except Exception as err:
    print(type(err))